# Generated by Django 4.2.7 on 2024-01-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_text', models.TextField(help_text='Текст показывющийся при страрте бота', verbose_name='Приветственный текст')),
                ('ban_text', models.TextField(help_text='Текст в случае если пользователь забанен', verbose_name='Бан-текст')),
                ('link_text', models.TextField(help_text='Текст для вступления в группу', verbose_name='Текст вступления в группу')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
