# Generated by Django 3.2.23 on 2024-01-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Название страны')),
                ('start', models.CharField(help_text='Писать без будто бы есть +. Т.е. код России "7"', max_length=16, verbose_name='Старт у номера')),
                ('is_allowed', models.BooleanField(default=False, verbose_name='Разрешенный ли номер')),
            ],
            options={
                'verbose_name': 'Номер телефона',
                'verbose_name_plural': 'Номера телефона',
            },
        ),
    ]
