# Generated by Django 3.2.23 on 2024-03-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='number',
            options={'verbose_name': 'Номер телефона', 'verbose_name_plural': 'Номера телефонов'},
        ),
        migrations.AlterModelOptions(
            name='yellowleaf',
            options={'verbose_name': 'Список проверки', 'verbose_name_plural': 'Список проверки'},
        ),
        migrations.AddField(
            model_name='people',
            name='donated',
            field=models.BooleanField(default=False, verbose_name='Донатил ли'),
        ),
        migrations.AddField(
            model_name='people',
            name='has_immune',
            field=models.BooleanField(default=False, verbose_name='Имунитет к автобану'),
        ),
    ]
