# Generated by Django 4.2.7 on 2023-12-03 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_people_options_alter_peopletobans_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения админа'),
        ),
        migrations.AlterField(
            model_name='peopletobans',
            name='ban',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.ban', verbose_name='Вид банна'),
        ),
        migrations.AlterField(
            model_name='peopletobans',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата бана'),
        ),
    ]
