# Generated by Django 4.2.7 on 2023-12-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_admin_created_at_alter_peopletobans_ban_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='ID пользователя в Телеграмме')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Telegram ID',
                'verbose_name_plural': 'Telegram ID',
            },
        ),
        migrations.AddField(
            model_name='people',
            name='telegram_id_list',
            field=models.ManyToManyField(to='user.telegramid', verbose_name='ID пользователя в Телеграмме'),
        ),
    ]
