# Generated by Django 4.2.7 on 2023-12-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_peopletomessage_remove_people_telegram_id_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopletomessage',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата регистрации'),
        ),
    ]
