# Generated by Django 4.2.7 on 2023-12-10 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_peopletomessage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopletomessage',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата последнего сообщения'),
        ),
        migrations.CreateModel(
            name='YellowLeaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('ban', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.ban', verbose_name='Вид возможного банна')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.people', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подозрительный пользователь',
                'verbose_name_plural': 'Подозрительные пользователи',
            },
        ),
    ]
