# Generated by Django 4.2.7 on 2024-01-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_peopletomessage_created_at_yellowleaf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yellowleaf',
            options={'verbose_name': 'Желтый список', 'verbose_name_plural': 'Желтый список'},
        ),
    ]
