# Generated by Django 4.2.7 on 2024-01-05 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_yellowleaf_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldDataPeople',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.people')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата смены данных пользователя')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_data_people', to='user.people', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Старые данные о пользователе',
                'verbose_name_plural': 'Старые данные о пользователе',
            },
            bases=('user.people',),
        ),
    ]
